import { sidebar } from "vuepress-theme-hope";
export default sidebar([
  "/DailyRoutine",
  "/Fitness",
  // docsify不能使用相对链接
  { text: "读书笔记", icon: "read", link: "https://me.bcfead.com/reading/" },
  // 指定显示页面
  {
    text: "🧰 应用手册",
    icon: "",
    prefix: "/apps/",
    link: "",
    collapsible: true,
    children: [
      "Applist.md",
      "ChatGPT.md",
      "design.md",
      "AppNotes.md",
      "Chrome.md",
      {
        text: "直播手册",
        icon: "load",
        prefix: "livestreaming/",
        link: "",
        collapsible: true,
        children: "structure",
      },
    ],
  },
  {
    text: "🌐 页面开发",
    icon: "",
    prefix: "/web/",
    link: "",
    collapsible: true,
    children: "structure",
  },
  {
    text: "🏗️ 网站部署",
    icon: "",
    prefix: "/deploy/",
    link: "",
    collapsible: true,
    children: [
      "Static.md",
      "CloudServices.md",
      "VPS.md",
      {
        text: "部署工具",
        icon: "emmet",
        collapsible: true,
        children: ["GitHub.md", "Cloudflare.md", "MySQL.md", "DNS.md"],
      },
    ],
  },
  {
    text: "🚀 代码学习",
    icon: "",
    prefix: "/code/",
    link: "",
    collapsible: true,
    children: [
      "README.md",
      {
        text: "Basic",
        icon: "emmet",
        collapsible: true,
        children: ["Markdown.md", "Electron.md", "AutoHotkey.md", "Regex.md"],
      },
      {
        text: "FrondEnd",
        icon: "app",
        collapsible: true,
        children: ["Vue.md", "HTML.md", "JavaScript.md", "Python.md"],
      },
    ],
  },
  {
    text: "🐋 Linux 服务",
    icon: "",
    prefix: "/services/",
    link: "",
    collapsible: true,
    children: "structure",
  },
  {
    text: "🪟 系统问题",
    icon: "",
    prefix: "/windows/",
    link: "",
    collapsible: true,
    children: "structure",
  },
  {
    text: "🛖 生活记录",
    icon: "",
    prefix: "/family/",
    link: "",
    collapsible: true,
    children: "structure",
  },
  {
    text: "博客文章",
    icon: "blog",
    prefix: "/_posts/",
    link: "/blog",
    collapsible: true,
    children: "structure",
  },
]);
